# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/model.proto\x12\x0cmlservice.v1\"\x0f\n\rHealthRequest\"6\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cmodelVersion\x18\x02 \x01(\t\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\"O\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x14\n\x0cmodelVersion\x18\x03 \x01(\t2\xa0\x01\n\x11PredictionService\x12\x43\n\x06Health\x12\x1b.mlservice.v1.HealthRequest\x1a\x1c.mlservice.v1.HealthResponse\x12\x46\n\x07Predict\x12\x1c.mlservice.v1.PredictRequest\x1a\x1d.mlservice.v1.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=36
  _globals['_HEALTHREQUEST']._serialized_end=51
  _globals['_HEALTHRESPONSE']._serialized_start=53
  _globals['_HEALTHRESPONSE']._serialized_end=107
  _globals['_PREDICTREQUEST']._serialized_start=109
  _globals['_PREDICTREQUEST']._serialized_end=143
  _globals['_PREDICTRESPONSE']._serialized_start=145
  _globals['_PREDICTRESPONSE']._serialized_end=224
  _globals['_PREDICTIONSERVICE']._serialized_start=227
  _globals['_PREDICTIONSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
